### PR TITLE
Add Ukrainian translation

### PR DESCRIPTION
**Pull request by andmizyk**

### CODE REVIEW

**Comment by davidbannon** [comment]
Hey, thats really great andmizyk, I need to merge back a new in note 'find' model from its own branch and then I will merge this one of yours.

I hope to put out a new release soon, will have a range of speed ups and better searching and finding capabilities. AND a Ukrainian translation !  Hopefully no further changes to language before then but we might need a few tweaks. 

Thanks, great news !

Davo

**Comment by andmizyk** [comment]
OK, until then I'll translate documentation too.

**Comment by davidbannon** [comment]
Great andmizyk, just don't do these ones -
* tomboy-ng.note  - I need to update the command line options, won't be long.
* tomdroid.note - plan to drop this out at the next release, its clunkly and does not seem to habe any users.

I'll let you know when tomboy-ng.note is all fixed up.

Thanks heaps !
Davo

**Comment by davidbannon** [comment]
OK andmizyk, help notes up to date. But I would recommend you don't bother with the tomdroid.
Davo

**Pull request merged**
