### PR TITLE
UI translation update

### PR DESCRIPTION
**Pull request by aguador**
Update of Spanish translation for upcoming v. 0.29

### CODE REVIEW

**Comment by davidbannon** [comment]
Thanks for this, brilliant timing !

I am finding it a bit strange however, Git seems to want to have you re-commit all the content I have posted since the last release.  I browsed through, no unexpected changes so no problems but seems a strange way to think about it.  I did the notes section first to see what it would do, it now shows me as having made the last change to the notes.zip file, about 12 hours ago, in fact that change happened in May !  
Please pull down the current spanish help notes and see if they contain what you expect.   
I did so myself and it looks to me (given my complete lack of spanish ability) that it is correct, so I have no idea why git should show me making the last change.  And that makes tracking changes rather hard ....

I'll hold off with this one until I hear from you.

I just found (yet another) bug in Single Note Mode so no rush !

Davo

**Comment by aguador** [comment]
Yep, there is a problem, probably related to my clumsiness with Git. Diffutils says that the .po showing as having been updated yesterday is not the update I committed. Actually that can be seen in the header where the earlier version of poedit is cited and v. 0.25 instead of 0.29.

It was also strange yesterday when I downloaded and opened the .po  that a number of strings showed as needing review/update that were correct. I suppose that could have come from "touching" something in the code, but it was strange.

I can try to commit again if you like, but do not have access to my main machine at the moment. You may see this in your e-mail. Will check the help files later. Sign!

**Comment by aguador** [comment]
The two changed help files are fine. My main machine is otherwise in use, so will e-mail the .po. Maybe one day I will figure out what I am doing wrong.

**Comment by aguador** [comment]
Just checked and found that the file in my machine's tomboy-ng directory is the old one. However, it is time-stamped an hour later that the translated file (saved in a subdirectory with other translations). Somehow I screwed up the commit and it seems I over-wrote the file I translated with the the one in the master branch. Maybe with the second, help file commit did it as the help file is stamped two minutes earlier than the .po file?

I thought I saw that it was better to make individual commits, so created two branches for the .po and help file commits and did them separately. Is that where I went wrong?

Will try to get it right for 0.30!

**Comment by davidbannon** [comment]
Hmm, I did merge the one with the help files, it told me you were changing heaps of files and while there was no content changed, the stamps were all updated. But when I merged back down to my local copy, only the spanish help files zip was updated, as it should be ???

I really don't understand.....

Davo

**Comment by aguador** [comment]
Wish I understood.

I downloaded the help file zip you merged and they were OK. The only changes: one new key shortcut and the write up on sshfs.

**Pull request closed without merging**
