### PR TITLE
Rename properly sync functions for further work on the sync process

### PR DESCRIPTION
**Pull request by grosjo**

### CODE REVIEW

**Comment by davidbannon** [comment]
I note this was posted before I answered your question with some advice about about senseless and destructive changing names of identifiers.  If you wish to be a bit co-operative and ensure a less difficult merge later on, close this pull request, else, tell me you don't care and I will merge it.
Davo

**Comment by davidbannon** [comment]
Please note, I am not suggesting the current names are necessarily good *, just that changing them before we merge will only make our task harder.
Davo

* that code was pretty much developed experimentally, the underlying sync algorithm was not documents, I worked it out by trial and error.  So, purpose of some methods did gradually change over time.

**Comment by grosjo** [comment]
Hi
Will you move forward on this ? I would like to finish the sync process update

**Comment by davidbannon** [comment]
Sure, if you insist. I was waiting to see if you would apply some common sense first.

Change what ever you like. But as I said before, you need to work on oauth.pas, transnet.pas and ncsetup.pas (?) not making random changes to existing code. Else it will be too hard to merge.  (I question ncsetup because I don't think its necessary.)

I have been looking at a separate, stand alone, command line driven test bed for the files I mentioned.  If you want to outline that approach, happy to oblige. 

In either case, I assume your code has not been tested, as checked in, it has some memory leaks and spots that will trigger bad crashes.  

David

**Pull request merged**
