### PR TITLE
Fix memory leaks & Further settings cleaning && Sync process overhaul

### PR DESCRIPTION
**Pull request by grosjo**

### CODE REVIEW

**Comment by davidbannon** [comment]
I will merge this request when you have responded to my questions about branch renaming.
David

**Comment by grosjo** [comment]
No question so far

Note : There is a load of changes upcoming , in order to fix the current setup.

**Comment by davidbannon** [comment]
do you understand what I mean about the branch renaming ?

You will have to send any more changes you have made, I merge them, **then you make no changes, advise me you are ready,** I will make the branch name change, you will then need to checkout the **netsync branch**.  

If you refuse to communicate it will all go wrong, do you understand ?

David

**Comment by grosjo** [comment]
Please , don't get angry at every message. 
(a) I have never got any "question" from you about branching.
(b) This is enormous work to clean the code and make things a bit more usable to add capabilities

Branch :No, this must be the master. The code need complete overhaul et this is what is in this PR

**Comment by davidbannon** [comment]
>  (a) I have never got any "question" from you about branching.

Please see the message I posted at the end of 'discussion' in your last pull request -
https://github.com/tomboy-notes/tomboy-ng/pull/178

And duplicated in the issues list -

https://github.com/tomboy-notes/tomboy-ng/issues/141#issuecomment-622615247


> (b) This is enormous work to clean the code and make things a bit more usable to add capabilities

Enormous indeed, but IMHO unnecessary.

> Branch :No, this must be the master. The code need complete overhaul et this is what is in this PR

You cannot be allowed to submit code to Master. The one pull request you sent that targeted master that I (stupidly) let through took me a day to correct. Your code is alpha code, there is no way it belongs in master. End users and distro maintainers download that code and expect a working system. Code needs to be well tested before it goes to master.

At present you are sending pull requests to 'release', a branch I made to try and get 0.28 out but you targeted before I could even use it !  People expect stable, tested code in branches with names like 'master' and 'release'.  Yours is not stable, tested code.

I am sorry, I do think your whole approach is wrong.  You have submitted at most a few hundred lines of code that actually deal with the problem you are trying to solve. Instead, you jump around changing existing, working code that makes the whole project unstable. 

I pushed my early attempt to  connect to grauphel (to master only, I don't push to your branch), its in experimental/netsync.  If you look at that, you will see how its possible to try to solve the target problems without being distracted by irrelivent things. I made little or no progress because I could not get OAuth to work but it shows you how to do focus on the target problem.

I am still waiting for you to advise me when I can rename your branch.

David

**Comment by grosjo** [comment]
David

This PR implements Nextcloud from A to Z. You have it in front of you.


It cleans also all the inconsistencies in the code, including :
(a) Putting a proper standardized approach common to all "trans' : loading 
data from remote in memory instead of copying useless filed
(b) Making the code able to handle multiple ServerID for sync without 
breaking (i.e. one manifest per ServerID)
(c) Removing incorrect direct access to management data (NoteMetaData)
(d) Streamlining Clash management (improper loops)
(e) Adding the " Make copy" as in old tomboy
(f) Separating properly what belngs to local from what is from transport data

So you have the solution

It does need further testing , but the core changed are in place and 
Nextcloud is working

**Comment by grosjo** [comment]
Not to mention that I did not spent my weekend on this "for fun" or "for pride" or for any philosophical reasons, as you seems to accuse me of, but just because I need the nextcloud part to work.

Same as when you go to dentist, before replacing a teeth, you need to remove the old broken stuff. In this case, the numbers of broken parts was huge. 

Please let's move forward . 

I will continue testing next week-end, and provide additional commits. 

About your 0.28, then branch out the actual master to a "0.28" branch in order to release it, and let the master move on new development. This is the normal way to work with Git

**Pull request merged**
