### PR TITLE
doc: fix missing newline for correct Markdown rendering in Github

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Comment by davidbannon** [comment]
monperrus, sorry to do this but really bad experience getting code into debian due to an unclear license.  So, can I please ask you to look at https://github.com/tomboy-notes/tomboy-ng/wiki/Contributions-and-Feature-Requests ?   It says that you are assigning your copyright to me.  (My policy will be that its all mine (!!) unless new content consists of, say, 100 lines or more.)

Davo

**Comment by monperrus** [comment]
I agree to give the copyright of this pull-request to you :) Thanks for 
your work!

**Comment by davidbannon** [comment]
Sorry I have not dealt with this, I am a bit puzzled about it in fact. You seem to have added a newline after the image.  From memory there was originally one there and I removed it because there was too much white space there, IMHO.
Does it not render properly on your system ?
Davo

**Comment by monperrus** [comment]
It is not rendered well on Github directly, see the bottom of the README page at https://github.com/tomboy-notes/tomboy-ng/

**Comment by davidbannon** [comment]
Strange, it looks fine on everything I look at it with. What OS/Browser are you using please ?
Davo

**Comment by monperrus** [comment]
Do you see non-rendered markup ` [Wiki](tomboy-notes/tomboy-ng/wiki) ` at the end of the page? This is the rendering problem fixed here.

**Comment by davidbannon** [comment]
Wow, I wonder how many times I have looked at that and not realised what I was looking at ?

xypd made the icons and the images on that page and sent me the README to go with it. I removed that (IMHO unnecessary) line feed to reduce the white space. But viewing it here, on 'remarkable' shows more whitespace **without** the line feed !   But it does render correctly. I don't, and perhaps don't want to, understand the inner works of markdown !

Thanks for the pull request, I will use it.  If it makes github's md render happy, OK !

Davo

**Comment by monperrus** [comment]
Perfect, thanks a lot.

**Pull request merged**
