### PR TITLE
Recovery NC

### PR DESCRIPTION
**Pull request by grosjo**
It looks like my changes have not been applied somehow

### CODE REVIEW

**Comment by davidbannon** [comment]
Did you read my note ?   I have merged it into a new branch called 'next'.  
next

Please read my notes, I put a fair bit of effort into writing them and I think they might help you.

Davo

**Comment by davidbannon** [comment]
Hmm, interesting. I cannot read my notes.  I am sure I posted to this pull request.
......  ?
Davo

**Comment by davidbannon** [comment]
I don't know what has happened.  If I am not allowed to post to a closed pull request, I would expect some sort of warning .....

I really don't feel like writing it all again.  In summary -

Please pull from and push to the 'next' branch.  When you have some working code, we will try and merge manually, that will be easy or, if you keep writing to units outside your scope, hard. But we will manage one way or another.

Your code generates an exception right now because you create the OAuth object after the first call to checkconfig() in the Settings->formcreate().

The captions need to be updated on the two buttons that trigger setup, if its already setup, they should say "change ...".

The new button you have used is TButton, causes me problems on the Mac....

All those things (and more) were fixed in the stuff you choose to overwrite ....

Davo

**Comment by grosjo** [comment]
Hi David, 

Let's do it the easy way, 

(a) Avoid branching. I won't use it anyway. 

(b) I will push you a complete PR, once the process works end to end.
This /will/ have an impact on settings.pas, and other units of the
program very probably. You shall agree on this, otherwise I won't be
able to implement anything. 

On 2020-04-15 10:12, davidbannon wrote:

> I don't know what has happened. If I am not allowed to post to a closed pull request, I would expect some sort of warning ..... 
> 
> I really don't feel like writing it all again. In summary - 
> 
> Please pull from and push to the 'next' branch. When you have some working code, we will try and merge manually, that will be easy or, if you keep writing to units outside your scope, hard. But we will manage one way or another. 
> 
> Your code generates an exception right now because you create the OAuth object after the first call to checkconfig() in the Settings->formcreate(). 
> 
> The captions need to be updated on the two buttons that trigger setup, if its already setup, they should say "change ...". 
> 
> The new button you have used is TButton, causes me problems on the Mac.... 
> 
> All those things (and more) were fixed in the stuff you choose to overwrite .... 
> 
> Davo 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/tomboy-notes/tomboy-ng/pull/168#issuecomment-613919318
[2]

**Comment by davidbannon** [comment]
Yeah, sure.  I cannot guarantee I will be able to accept a pull request some time down the track but I will try. Make a descendant of trans.pas work and I can graft back in one way or another.

My guess is you will need some changes 'upstream' to trans.pas, if you would like, you are welcome to discuss them.  Maybe a few new changes to settings wrt the config file.  There should, I believe be little or no reason to change other units. You may find otherwise. 

I wish you luck !

Incidentally, did you see this -
https://github.com/tomboy-notes/tomboy-ng/wiki/X-Sync-Model   ?

Davo

**Comment by grosjo** [comment]
Ok 

Can you at least apply this PR ?

On 2020-04-15 11:34, davidbannon wrote:

> Yeah, sure. I cannot guarantee I will be able to accept a pull request some time down the track but I will try. Make a descendant of trans.pas work and I can graft back in one way or another. 
> 
> My guess is you will need some changes 'upstream' to trans.pas, if you would like, you are welcome to discuss them. Maybe a few new changes to settings wrt the config file. There should, I believe be little or no reason to change other units. You may find otherwise. 
> 
> I wish you luck ! 
> 
> Incidentally, did you see this -
> https://github.com/tomboy-notes/tomboy-ng/wiki/X-Sync-Model ? 
> 
> Davo 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/tomboy-notes/tomboy-ng/pull/168#issuecomment-613959055
[2]

**Comment by grosjo** [comment]
All my work is gone again !
This is getting very very troublesome

**Comment by davidbannon** [comment]
>Can you at least apply this PR ?

As I said, I have applied this PR to the 'Next' branch of my github repo.  I cannot apply it o my main branch as I absolutly must get that ready for the next release, already a week later that I promised.

>All my work is gone again !

Have you sorted all this out ?

>This is getting very very troublesome

Indeed.
Davo

**Pull request closed without merging**
