### PR TITLE
Nextcloud : OAuth process & Sync implementation

### PR DESCRIPTION
**Pull request by grosjo**
Hopefully you will agree to push this into /master/ and keep my updates

Screenshot from 2020-04-17 22-33-22
Screenshot from 2020-04-17 22-33-10

### CODE REVIEW

**Comment by davidbannon** [comment]
You don't seem to understand how it all works grosjo.  I will try to explain again. Please read what I say here and if something does not make sense, ask me about it. I mean that, we can resolve these issues with discussion!

I am half way through the final test of the app before I make the next release. This release is important because it fixes a bug that only shows up in Ubuntu20.04, itself due for a release in a few days.  I must have my fix out before Ubuntu releases 20.04 !

I have three more platforms to test against, if I merge your code, I will have to start my test plan all over again, as I have done several time already. As there may be things in your code that break other systems, and you object to any changes I make, merging now would absolutely kill my release.  Ubuntu is the most widely used desktop linux, U20.04 is the long term release, if I mess this up, I may as well walk away from the whole project.

**Thats why I made a new branch and suggested you use and commit to that branch.  Doing so is easy, one command before you start to set your default to that branch.  Thats the normal way people work on experimental code in an existing project.  You cannot have experimental code popping up in production code especially in the middle of a release cycle.**

So, no, I cannot merge your code now, in a few days, after release, I will look at it but to merge now would be fatal !  

Rather than wait until after Sunday, my time, if you want to merge now, please merge to the 'next' branch, it already contains all the code you still seem to think you have lost. 

Davo

PS - can you please let me know when you have seen this message, I seem to have a problems sometimes posting comments in the pull request section, most strange. (I have even kept a copy this time !)  I will be off line most of this day now, sorry.

PS2 - please understand I really want and value your help here with is project, you apparently understand this aspect and have and use NextCloud. I don't !  I am quite unlikely to implement NextCloud and end users do want it.  But we must learn to work together using the tools git and github provide us to do just that.

**Comment by grosjo** [comment]
@davidbannon 

Finish your testings as much as you want, no hurry.

Now, these changes I am pushing here, impact the settings.pas and other files in order to get things right for multiple Sync processes (including Nextcloud then). 

This needs to go in master, there is no way around it.

If you want to do it /after/ your release, fine, but if we want things to move forward, please no branching. "merging branch" is too much subjective, and I really don't want to do things over and over.
Thank you

**Comment by davidbannon** [comment]
OK, that will work as long as you can assure me you have tested all GUI aspects on the following -
* Mac, Cocoa
* Mac, Carbon (although will probably drop this soon)
Win32, early widget set, eg Windows 7
Win10
Linux using GTK2, Qt5, ideally on at least Fedora, Ubuntu, Mageia, Debian and OpenSUSE
And it needs to be tested with normal system fonts and with fonts enlarged by 50%

We also need to be very careful not to change text used in the GUI any more than absolutely necessary because every change requires translation. And I only have so much credit with my translator.

While I don't have time right now to go over your request, I have scanned over it quickly. Your code looks good but I am very upset about the way you keep changing existing, working code with out discussing the changes, without even an explanation of why. 

I keep asking you to discuss your changes before making them and you ignore me. I ask you to make smaller pull requests so I can manage the changes, you ignore me. 

So, I now suggest you stop hacking into existing, working code and concentrate on implementing a NextCloud Sync.  Meanwhile, I will endeavor to look at your proposed changes, try and understand why they are necessary and decide how your needs can be accommodated.

Davo

**Comment by grosjo** [comment]
@davidbannon I can not ask your "approval" for any line I am changing. Otherwise, I will do this for ages and won't finish ever
You need to agree that other people contribute to the app, otherwise, you shall do all this alone.

**Comment by grosjo** [comment]
The core purpose of a PR is that the owner of the app can review changes before merging. 

If something seems really wrong, then you, as the owner, may ask changes to the coder before pushing the PR

This is the normal way to work on Github.

PLease confirm

**Comment by grosjo** [comment]
@davidbannon I pused also changes in tomdroid and filesync, in order to strealine the use of TsyncTranc accros several sync processes (no adhoc params, but all in one TStringList)

**Comment by davidbannon** [comment]
TB-Release
Your pull request targets 'release' not 'master'. I have not been able to alter the target of a pull request made by someone else, not sure its allowed.
Only way around that is to alter the names of the branches and then merge. If branches have diverged, very unsafe to try and trick git like that.
So, I have merged to 'release'.
As you have hacked in to just about every file present, merging will be difficult.  Thats why we practice "change control".

**Pull request merged**
