### PR TITLE
Let's try again

### PR DESCRIPTION
**Pull request by grosjo**

### CODE REVIEW

**Comment by davidbannon** [comment]
And you ask me why I get angry ?

This pull request targets **master**.   As I have explained several time, you cannot push code into master.

Have you checked out master or netsync ?    I did ask you if you understood the process (several times) but you just refuse to answer my question.  So, still thinking about having my code compared to a rotten tooth, I proceeded as I had explained I needed to.

I also believe that avoiding too large a merge is a good idea. I am pretty sure thats what went wrong earlier today with number 180.  Avoid adjusting formatting or altering the spelling in comments for example. 

Anyway, i cannot possibly merge this request.

David

**Comment by davidbannon** [comment]
I have just looked at a few randon tests and it appears to me that all the changes you requested in pull request 180 are in fact present in the netsync branch.

**Comment by grosjo** [comment]
Don't really care about netsync branch 

This shall be pushed to master , in order to be included in others' work

**Comment by davidbannon** [comment]
I am sick of saying this, this code is alpa code, it does not belong in master, I will not merge it with master !    I cannot make that any clearer. It will not go directly into master.

I will test it, try and understand it, if I can understand and find a way to convince myself that it works as expected and, more importantly, does not put end user's data at risk, I will merge some, or even all to master. But, thats going to be very hard, Why ? Because you have made so many changes, don't comment your code, don't respect what is already there and working, have not documented your reason  for quite arbitrary changes and have already demonstrated some very careless commits and have demonstrated a very worrying inability (or unwillingness) to communicate.

I will have to build another nextcloud platform and then try and see what I can do. 

You must understand, I have users out there with 20,000 notes, they cannot and will not be put at risk.

Please do not demand I merge to master again !  It will not happen, I have said this repeatedly, ignoring what I say will not alter my position.

David

**Comment by grosjo** [comment]
Master IS the location of alpha/cutting edge code 

Branching is for release and related maintenance 

If you do not understand coding and git, let people do it for you
instead of blocking everything 

If you do not accept colleborative work (especially as your code is
really a mess !), then whatever, be happy alone

**Comment by davidbannon** [comment]
I did create a release branch if you remember, then, you targeted it with another barrage of changes. (pull request 168 targeted 'release'). Me being a trusting sort of person (then), I let it through without checking which branch it was aimed at.

Anyway, if, as you believe I don't understand coding or git, I am quite sure you do not want to work with me.  Go and release your own version of tomboy-ng, make sure you give it a new name and I will refer anyone who who wants to use a grauphel/NextCloud/Apache stack to you. Personally, I would use sshfs, trivial install, nothing that needs maintenance, fast and reliable.

I would like to be able to say it has been a pleasure working with you but it most certainly has not.

David

**Comment by grosjo** [comment]
Then please do remove the netsync branch and any of my work I sent to you

**Comment by davidbannon** [comment]
done.
D

**Pull request closed without merging**
