### PR TITLE
Add keyboard shortcuts for font formatting

### PR DESCRIPTION
**Pull request by benjbrandall**
These mirror Tomboy's

### CODE REVIEW

**Comment by davidbannon** [comment]
Sorry if you see this twice Ben, looks like I cannot 'reply' directly from my email client to a pull request cnversation. Anyway, last night (my time) I said -

Ben, have you checked these out on the Mac as well ?

And I wonder if we should have hints about the short cuts on the menus ?  You know, -
copy ^C
Now, I _think_ that lazarus has some direct support for shortcuts in the Object Inspector, don't know. I, personally, rarely use keyboard shortcuts other then x,c and v. Probably because I m more comfortable using the command line...

Anyway, what you have here is good, makes sense, want me to run with it now or wait and see if we can followup with those hints ?
Davo

**Comment by davidbannon** [comment]
yeah, in edit box, switch to object inspector, select PopupText, select eg MenuBold, look at its properties. There are two short cut key properties.
She who must be obeyed say we are going out .....
David

**Comment by benjbrandall** [comment]
I've tested on Mac (using ctrl works fine, but I'd imagine most people expect it to be done with cmd -- enhancement to think about later?), and added shortcut hints to the menu with #59

**Comment by davidbannon** [comment]
Ah, well timed. Ben, when you say you have added shortcut hints to the menu, I think adding the key to the property takes care of calling the function too. I think ...
Wondering if that means a review of the whole set of shortcuts in in order.
Might setup a little project to experiment.
Davo

**Comment by benjbrandall** [comment]
I thought that it would too, but I didn't see any automatic modifications to the editbox.pas file as expected.

It claims that it's of type TShortCut but outside of the .lfm there's no modifications or mentions of that. I think Lazarus leaves this part up to us

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by davidbannon** [comment]
So, I just tried a test app.
Made a popup menu (that pops up with a right click of a button). Added a menu item and set it to print a message. Test - run the app, click the mutton, choose the only menu item, see the message.
OK, now add Ctrl B as that menu item's shortcut property. Now, when you run, click the menu you see the origional caption and Ctrl B.
So, no menu active, press Ctrl B and I see the same message as I see if I go through the menus.
So, no watching for a special key press is necessary. But we do need to make sure the real function that responds does not do so at a bad time ?
Davo

**Comment by davidbannon** [comment]
Here it is, bottom of my test unit's lfm file -
..... 
 object PopupMenu1: TPopupMenu
    left = 56
    top = 376
    object MenuItem1: TMenuItem
      Caption = 'MenuItem1'
      ShortCut = 16450
      OnClick = MenuItem1Click
    end
  end
....
Note the shortcut=16450 line, thats to tell the compiler to setup whatever is necessary to watch for key 16450 (which I assume is ^B) and deal with it, ie, call the onClick event handler.
I reckon doing stuff like that is probably quicker and, maybe easier to keep track of. Less code in unit1.pas anyway.  We'll still need a custom function to do handle some special things, especially around bullets (##@#!) but overall it would make for cleaner code IMHO.
Thoughts ?
David

**Comment by benjbrandall** [comment]
Sounds better to me if it avoids checking through more lines each time a key is pressed, cool!

**Comment by davidbannon** [comment]
Ben, need to move on here, I am running out of time. So, I had a play with the model we discussed but found it did not work as expected. The selected text is overwtitten with an unidentified char. I suspect it relates to the fact that we are not resetting the key to zero when we allow the menu item alone deal with it.
So, until we better understand whats happening, I have done a version of what you were suggesting plus setting the lfm so we still see the hint. It works fine but has not saved us the tin=me looking at that keypress each time. Think we can do better.
This has unfortunatly invalidated your pull requests - but reckon we need start from scratch anyway. Go off into a small app and determine just what the issue is.

**Comment by davidbannon** [comment]
Hmm, I keep forgetting that I cannot reply to these messages via email. Don't know what happens to them when I do ...

Yep, I think whats happening is that because we do it when some text is selected, pressing eg ^B replaces that text with a ^B, same as it would if you hit a normal key. What might be interesting is to try and see what order the various things happen in. So, a debugln in both the KeyDown event and the one mentioned in the Menu item ?

> If so, apparently it can be overridden with "the form property for "KeyPreview" set to true", e.g.:

Totally new to me !
OK. I sure would like to see that cleaner approach but am worried about time. I don't think I will be able to do much on the project after Thursday my time. While its grotty, I suggest it stay as it is until release and then you can have a go at making it work like it should.

Davo

**Pull request closed without merging**
