### PR TITLE
Add Ukrainian translation of Help Notes

### PR DESCRIPTION
**Pull request by andmizyk**
tomdroid didn't touch

### CODE REVIEW

**Comment by davidbannon** [comment]
Wow, Andrij, thats fantastic !  Thanks You !
Please note you are now listed as a contributer.
Can you please give me an example of how to correctly write Ukrainian for the prompt that appears in settings ?
Davo

**Comment by andmizyk** [comment]
> how to correctly write Ukrainian

Українська

**Comment by davidbannon** [comment]
Andrij, an early release candidate at https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.34, look for the files marked 0.34d that have your translations.

Davo

**Comment by davidbannon** [comment]
Andrij, I am getting ready to release tomboy-ng v0.35, there are only two minor changes from the translation you provided a month ago, you may want to update it ?  Your call.

A question, to make communication easier, I would like to setup a tomboy-ng translator team on github, would you like to be part of that ?

Davo

**Pull request merged**
