### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by davidbannon** [comment]
Fantastic !   Thanks Vistaus

**Comment by davidbannon** [comment]
Hi Vistaus, a while ago you provided a Dutch translation for tomboy-ng, I was wondering if you could do an update ?  tomboy-ng is pretty stable now, last release was a year ago, I am just about to do another, version 0.35. 
Thanks, Davo

**Comment by Vistaus** [comment]
Hi Davo,

Sure, no problem! Thanks for notifying me! :-)

Regards,
Heimen Stoffels

Op di 25 okt 2022, om 4:11 a.m. schreef Davo:

**Comment by Vistaus** [comment]
Hi Davo,

Quick update: there were a lot of new strings, so it took me a little while to update the translation. I'm almost finished now and I'll post a PR tomorrow.

Regards,
Heimen Stoffels

Op wo 26 okt 2022, om 12:10 p.m. schreef Heimen Stoffels:

**Pull request merged**
