### PR TITLE
Recovery NC

### PR DESCRIPTION
**Pull request by grosjo**

### CODE REVIEW

**Comment by davidbannon** [comment]
You seem to have made a lot of changes settings.pas again. I did ask you to discuss any such changes before proceeding.
So, I cannot merge until I have been over the changes (to settings.pas) carefully. I cannot risk having to have to spend another day fixing things up this close to a release. 
Pretty late here so I don't think I will be ready to merge tonight. Sorry.
Davo

**Comment by grosjo** [comment]
Noting extra as before (outside ncsetup et oauth), just recovering the need for update in settings & co

**Comment by davidbannon** [comment]
In future, not this request, but in future, if you keep submit smaller change sets, it would make the process a whole lot more managable.  I am more than happy for you to have a free hand in those files that you are managaing, but I have to be very careful about things that affect the whole app, especially just before a release. And Settings.pas affects the whole app !
Davo

**Comment by davidbannon** [comment]
I am sorry but I really must question some things here. I have a duty of care to our users to manage change control, its just not happening here I am afraid.

Button1 in settings.pas ?  this seems to be a second sync setup button ?  I said I don't think we need two buttons. Please explain why we need two buttons when I had it working fine with one ?

The OnChange events for RadioFileSync see to have some unnecessary (and possibly bad) lines that do things like RadioSyncNC.checked := false; and RadioSyncNC.checked := true;.  Why are they there ?  The radio buttons change automatically when one of their number is pressed (as long as they are in the same groupbox).  This code was all working, why change it ?

SyncType has become a global var, is there a reason for that ?  It was a local to procedure last time I looked.  The settings unit already has too many globals, I have been gradually reducing them, turning them into properties and functions where possible.  I would prefer to look at a better way to do what you need here. Examining the state of the RadioButtons is an easy and quick way to workout what sync mode we are in.  If that does not work (why ?) I'd prefer to provide a property that does the same thing.

You have added a new config file entry, 'SyncNCKey', how is that treated at startup if there is no config file present or the user changes the config file location ?

Why remove my comment about us no longer using UseFileSync ?  Sigh ... That entry will remain in end user's config file indefinitely.  We cannot remove AFAIK.  Someone, in the future could spend a long time trying to workout why that entry is not working.

Significant changes require discussion, sorry !

Sorry, I am sounding quite negitive but we really need to minimise unnecessary changes at this stage and we must seriously justify any changes we do make.

David

**Comment by grosjo** [comment]
Sync NC Key : If the value is empty at startup, the value is populated by a MD5(Rand(...)). This is to stregthen the encryption (Old Tomboy hardcoded 'anyone' as encryption key, which is just insecure) 

On this topic , I will need to store also the Token pair acquired from NextCloud. I was thinking of adding them to the Gnome Keyring. If not, these are to go into the config file or similar

Radio button : 2 changes
(1) You have made so that at Radio change, the config is disabled ("xxx.caption = rsNotConfigure") . This is not correct. THe configuration stays, the use may use FileSync or NCSync at his convenience, without deleting in one click the configuration
(2) There has to be a flag somewhere to say wether the app use FileSync, NC or any other (Tomdroid and maybe others later). Relying on teh status of a radio button is really weird. So I put it into SyncType. You make change this as you wish, but somehow, there meus be avariable (outside the GUI) that stores the chosen Sync protocol

Sync config buttons : I don't understand why you keep on removing the NC button. There has to be a button to launch the OAuth process and this has nothing to do with the FileSync. And this has nothing to do with current status of the radio button. Once again, changing the radio shall not reset the Oauth config or FileSync config.  So, there are 2 buttons, can't go around mathematics. 

Hope this clarifies

**Comment by grosjo** [comment]
I need again to redo a PR, the GitHub is a total nightmare

**Pull request closed without merging**
